# Generated by Django 2.2.16 on 2022-12-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='category_id',
            new_name='category',
        ),
    ]
