# Generated by Django 2.2.16 on 2022-12-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('title_id', 'author')},
        ),
    ]
