# Generated by Django 4.1.3 on 2022-11-30 20:13

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_categories_options_alter_genres_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.PositiveIntegerField(db_index=True, validators=[reviews.models.validate_year]),
        ),
    ]
